require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe LojasController do

  # This should return the minimal set of attributes required to create a valid
  # Loja. As you add validations to Loja, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "nome" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # LojasController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all lojas as @lojas" do
      loja = Loja.create! valid_attributes
      get :index, {}, valid_session
      assigns(:lojas).should eq([loja])
    end
  end

  describe "GET show" do
    it "assigns the requested loja as @loja" do
      loja = Loja.create! valid_attributes
      get :show, {:id => loja.to_param}, valid_session
      assigns(:loja).should eq(loja)
    end
  end

  describe "GET new" do
    it "assigns a new loja as @loja" do
      get :new, {}, valid_session
      assigns(:loja).should be_a_new(Loja)
    end
  end

  describe "GET edit" do
    it "assigns the requested loja as @loja" do
      loja = Loja.create! valid_attributes
      get :edit, {:id => loja.to_param}, valid_session
      assigns(:loja).should eq(loja)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Loja" do
        expect {
          post :create, {:loja => valid_attributes}, valid_session
        }.to change(Loja, :count).by(1)
      end

      it "assigns a newly created loja as @loja" do
        post :create, {:loja => valid_attributes}, valid_session
        assigns(:loja).should be_a(Loja)
        assigns(:loja).should be_persisted
      end

      it "redirects to the created loja" do
        post :create, {:loja => valid_attributes}, valid_session
        response.should redirect_to(Loja.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved loja as @loja" do
        # Trigger the behavior that occurs when invalid params are submitted
        Loja.any_instance.stub(:save).and_return(false)
        post :create, {:loja => { "nome" => "invalid value" }}, valid_session
        assigns(:loja).should be_a_new(Loja)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Loja.any_instance.stub(:save).and_return(false)
        post :create, {:loja => { "nome" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested loja" do
        loja = Loja.create! valid_attributes
        # Assuming there are no other lojas in the database, this
        # specifies that the Loja created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Loja.any_instance.should_receive(:update).with({ "nome" => "MyString" })
        put :update, {:id => loja.to_param, :loja => { "nome" => "MyString" }}, valid_session
      end

      it "assigns the requested loja as @loja" do
        loja = Loja.create! valid_attributes
        put :update, {:id => loja.to_param, :loja => valid_attributes}, valid_session
        assigns(:loja).should eq(loja)
      end

      it "redirects to the loja" do
        loja = Loja.create! valid_attributes
        put :update, {:id => loja.to_param, :loja => valid_attributes}, valid_session
        response.should redirect_to(loja)
      end
    end

    describe "with invalid params" do
      it "assigns the loja as @loja" do
        loja = Loja.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Loja.any_instance.stub(:save).and_return(false)
        put :update, {:id => loja.to_param, :loja => { "nome" => "invalid value" }}, valid_session
        assigns(:loja).should eq(loja)
      end

      it "re-renders the 'edit' template" do
        loja = Loja.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Loja.any_instance.stub(:save).and_return(false)
        put :update, {:id => loja.to_param, :loja => { "nome" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested loja" do
      loja = Loja.create! valid_attributes
      expect {
        delete :destroy, {:id => loja.to_param}, valid_session
      }.to change(Loja, :count).by(-1)
    end

    it "redirects to the lojas list" do
      loja = Loja.create! valid_attributes
      delete :destroy, {:id => loja.to_param}, valid_session
      response.should redirect_to(lojas_url)
    end
  end

end
