require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PreferenciaController do

  # This should return the minimal set of attributes required to create a valid
  # Preferencium. As you add validations to Preferencium, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "produto" => "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PreferenciaController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all preferencia as @preferencia" do
      preferencium = Preferencium.create! valid_attributes
      get :index, {}, valid_session
      assigns(:preferencia).should eq([preferencium])
    end
  end

  describe "GET show" do
    it "assigns the requested preferencium as @preferencium" do
      preferencium = Preferencium.create! valid_attributes
      get :show, {:id => preferencium.to_param}, valid_session
      assigns(:preferencium).should eq(preferencium)
    end
  end

  describe "GET new" do
    it "assigns a new preferencium as @preferencium" do
      get :new, {}, valid_session
      assigns(:preferencium).should be_a_new(Preferencium)
    end
  end

  describe "GET edit" do
    it "assigns the requested preferencium as @preferencium" do
      preferencium = Preferencium.create! valid_attributes
      get :edit, {:id => preferencium.to_param}, valid_session
      assigns(:preferencium).should eq(preferencium)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Preferencium" do
        expect {
          post :create, {:preferencium => valid_attributes}, valid_session
        }.to change(Preferencium, :count).by(1)
      end

      it "assigns a newly created preferencium as @preferencium" do
        post :create, {:preferencium => valid_attributes}, valid_session
        assigns(:preferencium).should be_a(Preferencium)
        assigns(:preferencium).should be_persisted
      end

      it "redirects to the created preferencium" do
        post :create, {:preferencium => valid_attributes}, valid_session
        response.should redirect_to(Preferencium.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved preferencium as @preferencium" do
        # Trigger the behavior that occurs when invalid params are submitted
        Preferencium.any_instance.stub(:save).and_return(false)
        post :create, {:preferencium => { "produto" => "invalid value" }}, valid_session
        assigns(:preferencium).should be_a_new(Preferencium)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Preferencium.any_instance.stub(:save).and_return(false)
        post :create, {:preferencium => { "produto" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested preferencium" do
        preferencium = Preferencium.create! valid_attributes
        # Assuming there are no other preferencia in the database, this
        # specifies that the Preferencium created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Preferencium.any_instance.should_receive(:update).with({ "produto" => "" })
        put :update, {:id => preferencium.to_param, :preferencium => { "produto" => "" }}, valid_session
      end

      it "assigns the requested preferencium as @preferencium" do
        preferencium = Preferencium.create! valid_attributes
        put :update, {:id => preferencium.to_param, :preferencium => valid_attributes}, valid_session
        assigns(:preferencium).should eq(preferencium)
      end

      it "redirects to the preferencium" do
        preferencium = Preferencium.create! valid_attributes
        put :update, {:id => preferencium.to_param, :preferencium => valid_attributes}, valid_session
        response.should redirect_to(preferencium)
      end
    end

    describe "with invalid params" do
      it "assigns the preferencium as @preferencium" do
        preferencium = Preferencium.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Preferencium.any_instance.stub(:save).and_return(false)
        put :update, {:id => preferencium.to_param, :preferencium => { "produto" => "invalid value" }}, valid_session
        assigns(:preferencium).should eq(preferencium)
      end

      it "re-renders the 'edit' template" do
        preferencium = Preferencium.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Preferencium.any_instance.stub(:save).and_return(false)
        put :update, {:id => preferencium.to_param, :preferencium => { "produto" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested preferencium" do
      preferencium = Preferencium.create! valid_attributes
      expect {
        delete :destroy, {:id => preferencium.to_param}, valid_session
      }.to change(Preferencium, :count).by(-1)
    end

    it "redirects to the preferencia list" do
      preferencium = Preferencium.create! valid_attributes
      delete :destroy, {:id => preferencium.to_param}, valid_session
      response.should redirect_to(preferencia_url)
    end
  end

end
