require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PromocaosController do

  # This should return the minimal set of attributes required to create a valid
  # Promocao. As you add validations to Promocao, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "nome" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PromocaosController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all promocaos as @promocaos" do
      promocao = Promocao.create! valid_attributes
      get :index, {}, valid_session
      assigns(:promocaos).should eq([promocao])
    end
  end

  describe "GET show" do
    it "assigns the requested promocao as @promocao" do
      promocao = Promocao.create! valid_attributes
      get :show, {:id => promocao.to_param}, valid_session
      assigns(:promocao).should eq(promocao)
    end
  end

  describe "GET new" do
    it "assigns a new promocao as @promocao" do
      get :new, {}, valid_session
      assigns(:promocao).should be_a_new(Promocao)
    end
  end

  describe "GET edit" do
    it "assigns the requested promocao as @promocao" do
      promocao = Promocao.create! valid_attributes
      get :edit, {:id => promocao.to_param}, valid_session
      assigns(:promocao).should eq(promocao)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Promocao" do
        expect {
          post :create, {:promocao => valid_attributes}, valid_session
        }.to change(Promocao, :count).by(1)
      end

      it "assigns a newly created promocao as @promocao" do
        post :create, {:promocao => valid_attributes}, valid_session
        assigns(:promocao).should be_a(Promocao)
        assigns(:promocao).should be_persisted
      end

      it "redirects to the created promocao" do
        post :create, {:promocao => valid_attributes}, valid_session
        response.should redirect_to(Promocao.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved promocao as @promocao" do
        # Trigger the behavior that occurs when invalid params are submitted
        Promocao.any_instance.stub(:save).and_return(false)
        post :create, {:promocao => { "nome" => "invalid value" }}, valid_session
        assigns(:promocao).should be_a_new(Promocao)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Promocao.any_instance.stub(:save).and_return(false)
        post :create, {:promocao => { "nome" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested promocao" do
        promocao = Promocao.create! valid_attributes
        # Assuming there are no other promocaos in the database, this
        # specifies that the Promocao created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Promocao.any_instance.should_receive(:update).with({ "nome" => "MyString" })
        put :update, {:id => promocao.to_param, :promocao => { "nome" => "MyString" }}, valid_session
      end

      it "assigns the requested promocao as @promocao" do
        promocao = Promocao.create! valid_attributes
        put :update, {:id => promocao.to_param, :promocao => valid_attributes}, valid_session
        assigns(:promocao).should eq(promocao)
      end

      it "redirects to the promocao" do
        promocao = Promocao.create! valid_attributes
        put :update, {:id => promocao.to_param, :promocao => valid_attributes}, valid_session
        response.should redirect_to(promocao)
      end
    end

    describe "with invalid params" do
      it "assigns the promocao as @promocao" do
        promocao = Promocao.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Promocao.any_instance.stub(:save).and_return(false)
        put :update, {:id => promocao.to_param, :promocao => { "nome" => "invalid value" }}, valid_session
        assigns(:promocao).should eq(promocao)
      end

      it "re-renders the 'edit' template" do
        promocao = Promocao.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Promocao.any_instance.stub(:save).and_return(false)
        put :update, {:id => promocao.to_param, :promocao => { "nome" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested promocao" do
      promocao = Promocao.create! valid_attributes
      expect {
        delete :destroy, {:id => promocao.to_param}, valid_session
      }.to change(Promocao, :count).by(-1)
    end

    it "redirects to the promocaos list" do
      promocao = Promocao.create! valid_attributes
      delete :destroy, {:id => promocao.to_param}, valid_session
      response.should redirect_to(promocaos_url)
    end
  end

end
